services:
  web:
    build:
      context: ./BebraTemplate/
      dockerfile: докерфайл
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=your_database;User Id=your_user;Password=your_password;
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: bebrik
      POSTGRES_PASSWORD: bebriksecret
      POSTGRES_DB: sexdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

